# Generated by Django 4.1.1 on 2022-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('nonce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JGChain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blocks', models.ManyToManyField(to='JGChain.block')),
            ],
        ),
    ]
