# Generated by Django 4.1.1 on 2022-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JGChain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='current_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
