# Generated by Django 4.1.1 on 2022-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JGChain', '0003_alter_block_current_hash_alter_block_previous_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
